### ISSUE TITLE
Expose more details about torrent files

### ISSUE THREAD

**Issue by falzm** [cenkalti/rain#19]
Hi, I'm very interested in using this software, however I find it a bit terse regarding the files downloaded via the torrents. Could it be possible to expose more information via the RPC, such as file-level statistics (e.g. file list, size, % completion etc)? I'm thinking of trying to implement this in a fork and submit it to the original project for upstream integration if you're interested: if so, do you have tips as to where to start looking in the codebase?

Thanks! 😊

**Comment by falzm** [comment]
Another feature I'd be very to see implemented is a basic hook system to execute shell commands on torrent completion, e.g. to trigger downloaded file processing. Same deal, I can try to implement it if you think it can make it upstream.

**Comment by cenkalti** [comment]
Hi @falzm . That would be great to see this feature in Rain.

To implement file level statistics, you can add a new `rain client files` CLI command after `rain client peers` here:
https://github.com/cenkalti/rain/blob/324770b69a591fe925ec36b47ce342f44e414089/main.go#L239

Another option would be to add file level statistics into `rain client stats` command but I don't want to do that because currently it is very cheap to call `rain client stats` and I would like to keep it that way. Iterating over files and pieces can be slow on big torrents.

You can follow the same code path that is similar to `rain client peers` command for a guideline about the implementation. Please let me know if you have a specific question.

I'll create a separate to issue for your second comment to keep the discussion topics separate.
