### ISSUE TITLE
Execute shell commands on torrent completion

### ISSUE THREAD

**Issue by cenkalti** [cenkalti/rain#20]
... continues from https://github.com/cenkalti/rain/issues/19#issuecomment-877663931

Quoting @falzm:

> Another feature I'd be very to see implemented is a basic hook system to execute shell commands on torrent completion, e.g. to trigger downloaded file processing. Same deal, I can try to implement it if you think it can make it upstream.

Can we discuss this more before start implementing?
- How user specifies the command to run? Do you think to specify it in config file or specify as a argument when adding torrent? I think it will be simpler if we put it in a config and use the same command for every torrent that completes.
- Which variables do we pass to the script? Transmission passes [these variables](https://github.com/transmission/transmission/wiki/Scripts#on-torrent-completion)
- What kind of processing to you want to do? Is it going to be read-only? Rain assumes that torrents does not get modified by another program. If they get modified, Rain does not detect the change and uploads corrupt data, which is bad for you and the swarm.
- How will you handle script errors?

**Comment by falzm** [comment]
>     * How user specifies the command to run? Do you think to specify it in config file or specify as a argument when adding torrent? I think it will be simpler if we put it in a config and use the same command for every torrent that completes.

I was expecting it to be global to the session indeed. To keep the implementation and usage simple, I'd see a new configuration parameter accepting a list of strings describing the command and its parameters to pass to [`os/exec's Command()`](https://pkg.go.dev/os/exec@go1.16.5#Command). To prevent the hook's command to block the main loop, it should probably be spun in a goroutine.

>     * Which variables do we pass to the script? Transmission passes [these variables](https://github.com/transmission/transmission/wiki/Scripts#on-torrent-completion)

I'd like to add the location of the downloaded files from the torrent on disk, otherwise this set of information looks good to me.

>     * What kind of processing to you want to do? Is it going to be read-only? Rain assumes that torrents does not get modified by another program. If they get modified, Rain does not detect the change and uploads corrupt data, which is bad for you and the swarm.

In my case that'd be to symlink downloaded files to other locations and send the files for storage on remote locations once they are downloaded. I agree with you that the files *shouldn't* be altered post download, however if the users decide to do so it'll be at their own perils.

>     * How will you handle script errors?

It won't, IMHO since the post-download hook is an optional stage it shouldn't affect the core torrent handling operations – that principle also keeps the implementation simple by pushing the burden of error handling on the user.

**Comment by cenkalti** [comment]
Looks good to me. Please let me know if you need anything from me.

**Comment by cenkalti** [comment]
Closing this issue as it is addressed by #21 and https://github.com/cenkalti/rain/commit/65dbfb3c2c44f8d6f1ec7a3eae26048a2cf8d916 
Please let me know if anything is missing.
