### ISSUE TITLE
Should add timeout for udp trackers in PeriodicalAnnouncer

### ISSUE THREAD

**Issue by kylege** [cenkalti/rain#72]
When the Periodical Announcer call doAnnounce with context, the context has no timeout, so it will block when a udp tracker hangs in network.

And when udp tracker Announce hangs, it has connection lock, so then call torrent.Stop, the torrent.NotifyStop will hangs too.

So in a session, if any udp tracker hangs in network, the stop of any torrent task will hangs for a long time  (if these torrents share the same udp tracker, such as extra trackers list) , this is very bad.

Maybe, in internal/announcer/periodic.go, the ctx should be context.WithTimeout:

```golang
// Run the announcer goroutine. Invoke with go statement.

func (a *PeriodicalAnnouncer) Run() {
...
	ctx, cancel := context.WithCancel(context.Background())
...
```

**Comment by cenkalti** [comment]
When stopping a torrent, in order to prevent this scenario, first, `PerioidAnnouncer`s are stopped. This operation does not block.

https://github.com/cenkalti/rain/blob/fc79f0f92882e70a7bba13a8e84b9c6a9a6c818d/torrent/torrent_stop.go#L67

The torrent goes into Stopping state.

Then, another `Announcer` is started that will only announce one time, with a timeout of `TrackerStopTimeout` which is 5 seconds by default (but configurable via config file). This is required to tell the tracker that we are stopping the torrent and tell it to remove our client from the peer list.

https://github.com/cenkalti/rain/blob/fc79f0f92882e70a7bba13a8e84b9c6a9a6c818d/torrent/torrent_stop.go#L93

This still does not hang. If you don't want to wait for last announce, you can call `Torrent.Stop()` again to stop it immediately.

Do you experience a hang larger than `TrackerStopTimeout`?

**Comment by kylege** [comment]
Yes, i'm experience a hang larger than `TrackerStopTimeout`.

It's not the stopping torrent's PerioidAnnouncer that hangs, it's other running torrents's PerioidAnnouncer hang because of udp tracker.

All announcers share the same udptracker.Transport in TrackerManager

```go
type TrackerManager struct {
	httpTransport *http.Transport
	udpTransport  *udptracker.Transport
}
```

And there is one lock in udptracker.Transport

```go
func (t *Transport) getConnection(addr string) *connection {
	t.m.Lock()
	defer t.m.Unlock()
	conn, ok := t.connections[addr]
	if !ok {
		conn = new(connection)
		t.connections[addr] = conn
	}
	return conn
}
```

So when we get lock and hang in `Transport.retryTransaction`, then another torrent call `Transport.getConnection` will hang too.

```go
func (t *Transport) retryTransaction(ctx context.Context, f func(*transaction), trx *transaction) ([]byte, error) {
	t.m.Lock()      // this hang until udp tracker done, before that, all other torrents call getConnection will hang because of this lock
	t.transactions[trx.ID()] = trx
	t.m.Unlock()
...
}
```

Maybe i'm not right, but please check anyway, thanks.

**Comment by cenkalti** [comment]
I think I get this. I have a solution in my mind. I'll try to implement this weekend.

**Comment by kylege** [comment]
> I think I get this. I have a solution in my mind. I'll try to implement this weekend.

Hi @cenkalti ，is there any progress?

**Comment by cenkalti** [comment]
Sorry, I didn't have enough time. I'll try to look again this weekend.

**Comment by cenkalti** [comment]
Hey @kylege . This issue turned out to be a larger refactor rather that a small fix. I removed the lock completely and replaced it with a goroutine in UDP transport. I already merged it after testing on my own seedbox but feel free to comment and ask questions on the commit: https://github.com/cenkalti/rain/commit/33212782823d758deacaa43baa19b9b61ccb8507

Please let me know what do you think. Cheers!

**Comment by kylege** [comment]
> Hey @kylege . This issue turned out to be a larger refactor rather that a small fix. I removed the lock completely and replaced it with a goroutine in UDP transport. I already merged it after testing on my own seedbox but feel free to comment and ask questions on the commit: [3321278](https://github.com/cenkalti/rain/commit/33212782823d758deacaa43baa19b9b61ccb8507)
> 
> Please let me know what do you think. Cheers!

Nice work! Problem solved perfectly.
